#!MC 1400
# Created by Tecplot 360 build 14.0.2.35002
$!VarSet |MFBD| = '.'
$!READDATASET  '.\result.plt '
  READDATAOPTION = NEW
  RESETSTYLE = YES
  INCLUDETEXT = NO
  INCLUDEGEOM = NO
  INCLUDECUSTOMLABELS = NO
  VARLOADMODE = BYNAME
  ASSIGNSTRANDIDS = YES
  INITIALPLOTTYPE = CARTESIAN3D
  VARNAMELIST = '"X" "Y" "Z" "I" "J" "K" "U" "V" "W" "T" "fu" "fv"'
$!EXTENDEDCOMMAND 
  COMMANDPROCESSORID = 'CFDAnalyzer4'
  COMMAND = 'SetFieldVariables ConvectionVarsAreMomentum=\'T\' UVar=0 VVar=0 WVar=0 ID1=\'Pressure\' Variable1=10 ID2=\'NotUsed\' Variable2=0'
$!EXTENDEDCOMMAND 
  COMMANDPROCESSORID = 'CFDAnalyzer4'
  COMMAND = 'Calculate Function=\'PRESSUREGRADIENT\' Normalization=\'None\' ValueLocation=\'CellCentered\' CalculateOnDemand=\'F\' UseMorePointsForFEGradientCalculations=\'F\''
$!EXTENDEDCOMMAND 
  COMMANDPROCESSORID = 'CFDAnalyzer4'
  COMMAND = 'Integrate [1] VariableOption=\'Average\' XOrigin=0 YOrigin=0 ZOrigin=0 ScalarVar=13 Absolute=\'F\' ExcludeBlanked=\'F\' XVariable=1 YVariable=2 ZVariable=3 IntegrateOver=\'IPlanes\' IntegrateBy=\'Zones\' IRange={MIN =0 MAX = 0 SKIP = 1} JRange={MIN =1 MAX = 0 SKIP = 1} KRange={MIN =1 MAX = 0 SKIP = 1} PlotResults=\'F\' PlotAs=\'Result\' TimeMin=0 TimeMax=0'
$!EXTENDEDCOMMAND 
  COMMANDPROCESSORID = 'CFDAnalyzer4'
  COMMAND = 'SaveIntegrationResults FileName=\'Out_East.txt\''
$!EXTENDEDCOMMAND 
  COMMANDPROCESSORID = 'CFDAnalyzer4'
  COMMAND = 'Integrate [1] VariableOption=\'Average\' XOrigin=0 YOrigin=0 ZOrigin=0 ScalarVar=13 Absolute=\'F\' ExcludeBlanked=\'F\' XVariable=1 YVariable=2 ZVariable=3 IntegrateOver=\'IPlanes\' IntegrateBy=\'Zones\' IRange={MIN =1 MAX = 1 SKIP = 1} JRange={MIN =1 MAX = 0 SKIP = 1} KRange={MIN =1 MAX = 0 SKIP = 1} PlotResults=\'F\' PlotAs=\'Result\' TimeMin=0 TimeMax=0'
$!EXTENDEDCOMMAND 
  COMMANDPROCESSORID = 'CFDAnalyzer4'
  COMMAND = 'SaveIntegrationResults FileName=\'Out_West.txt\''
$!GLOBALCONTOUR 1  VAR = 4
$!CONTOURLEVELS RESETTONICE
  CONTOURGROUP = 1
  APPROXNUMVALUES = 15
$!GLOBALCONTOUR 1  VAR = 10
$!CONTOURLEVELS RESETTONICE
  CONTOURGROUP = 1
  APPROXNUMVALUES = 15
$!FIELDMAP [1]  SURFACES{SURFACESTOPLOT = EXPOSEDCELLFACES}
$!FIELDLAYERS SHOWCONTOUR = YES
$!REDRAWALL 
$!GLOBALTHREED SLICE{NORMAL{Y = 1}}
$!GLOBALTHREED SLICE{NORMAL{Z = 0}}
$!GLOBALTHREED SLICE{ORIGIN{Y = 0.5}}
$!GLOBALTHREED SLICE{NORMAL{Y = 0}}
$!GLOBALTHREED SLICE{NORMAL{Z = 1}}
$!GLOBALTHREED SLICE{ORIGIN{Z = 0.5}}
$!CREATESLICEZONEFROMPLANE 
  SLICESOURCE = VOLUMEZONES
  FORCEEXTRACTIONTOSINGLEZONE = YES
  COPYCELLCENTEREDVALUES = NO
$!GLOBALTHREED SLICE{NORMAL{Y = 1}}
$!GLOBALTHREED SLICE{NORMAL{Z = 0}}
$!CREATESLICEZONEFROMPLANE 
  SLICESOURCE = VOLUMEZONES
  FORCEEXTRACTIONTOSINGLEZONE = YES
  COPYCELLCENTEREDVALUES = NO
$!PLOTTYPE = CARTESIAN2D
$!TWODAXIS YDETAIL{VARNUM = 3}
$!REDRAWALL 
$!ACTIVEFIELDMAPS -= [1-2]
$!REDRAWALL 
$!CONTOURLEVELS RESETTONICE
  CONTOURGROUP = 1
  APPROXNUMVALUES = 9
$!REDRAWALL 
$!FIELDMAP [3]  CONTOUR{CONTOURTYPE = BOTHLINESANDFLOOD}
$!FIELDMAP [3]  CONTOUR{LINETHICKNESS = 0.40000000000000002}
$!REDRAWALL 
$!EXPORTSETUP IMAGEWIDTH = 1275
$!EXPORTSETUP EXPORTFNAME = '.\T.wmf'
$!EXPORT 
  EXPORTREGION = CURRENTFRAME
$!FIELDMAP [3]  CONTOUR{CONTOURTYPE = LINES}
$!REDRAWALL 
$!PICK ADDATPOSITION
  X = 9.46916299559
  Y = 2.6640969163
  CONSIDERSTYLE = YES
$!FIELDMAP [3]  CONTOUR{CONTOURTYPE = FLOOD}
$!REDRAWALL 
$!GLOBALTWODVECTOR UVAR = 7
$!GLOBALTWODVECTOR VVAR = 9
$!RESETVECTORLENGTH 
$!STREAMTRACE RESETDELTATIME
$!STREAMTRACELAYERS SHOW = YES
$!PICK SETMOUSEMODE
  MOUSEMODE = SELECT
$!STREAMTRACE ADD
  DISTRIBUTIONREGION = SURFACESOFACTIVEZONES
  NUMPTS = 50
  STREAMTYPE = TWODLINE
  STREAMDIRECTION = BOTH
$!REDRAWALL 
$!STREAMTRACE DELETEALL
$!FRAMESETUP NUMSTREAMSURFACEPOINTS = 30
$!STREAMTRACE ADD
  DISTRIBUTIONREGION = SURFACESOFACTIVEZONES
  NUMPTS = 30
  STREAMTYPE = TWODLINE
  STREAMDIRECTION = BOTH
$!REDRAWALL 
$!STREAMTRACE DELETEALL
$!FRAMESETUP NUMSTREAMSURFACEPOINTS = 20
$!STREAMTRACE ADD
  DISTRIBUTIONREGION = SURFACESOFACTIVEZONES
  NUMPTS = 20
  STREAMTYPE = TWODLINE
  STREAMDIRECTION = BOTH
$!REDRAWALL 
$!EXPORTSETUP EXPORTFORMAT = PNG
$!EXPORTSETUP IMAGEWIDTH = 1021
$!EXPORTSETUP EXPORTFNAME = '.\Streampline.png'
$!EXPORT 
  EXPORTREGION = CURRENTFRAME
$!STREAMTRACELAYERS SHOW = NO
$!REDRAWALL 
$!FIELDMAP [3]  CONTOUR{CONTOURTYPE = LINES}
$!REDRAWALL 
$!PICK ADDATPOSITION
  X = 8.67621145374
  Y = 4.30286343612
  CONSIDERSTYLE = YES
$!PICK ADDATPOSITION
  X = 8.80837004405
  Y = 3.17511013216
  CONSIDERSTYLE = YES
$!PICK CLEAR
$!PICK ADDATPOSITION
  X = 5.47797356828
  Y = 7.87114537445
  CONSIDERSTYLE = YES
$!TWODAXIS XDETAIL{SHOWAXIS = NO}
$!PICK ADDATPOSITION
  X = 1.46916299559
  Y = 4.30286343612
  CONSIDERSTYLE = YES
$!TWODAXIS YDETAIL{SHOWAXIS = NO}
$!REDRAWALL 
$!EXPORTSETUP EXPORTFORMAT = WINDOWSMETAFILE
$!EXPORTSETUP IMAGEWIDTH = 1275
$!EXPORTSETUP EXPORTFNAME = '.\T_publish.wmf'
$!EXPORT 
  EXPORTREGION = CURRENTFRAME
$!EXTRACTFROMPOLYLINE 
  EXTRACTTHROUGHVOLUME = NO
  EXTRACTLINEPOINTSONLY = NO
  INCLUDEDISTANCEVAR = NO
  NUMPTS = 400
  EXTRACTTOFILE = YES
  FNAME = '.\X.dat'
  RAWDATA
2
0.5 0.0 0
0.5 1.0 0
$!PICK SETMOUSEMODE
  MOUSEMODE = SELECT
$!EXTRACTFROMPOLYLINE 
  EXTRACTTHROUGHVOLUME = NO
  EXTRACTLINEPOINTSONLY = NO
  INCLUDEDISTANCEVAR = NO
  NUMPTS = 400
  EXTRACTTOFILE = YES
  FNAME = '.\Z.dat'
  RAWDATA
2
0.0 0.5 0
1.0 0.5 0
$!PICK SETMOUSEMODE
  MOUSEMODE = SELECT
$!ACTIVEFIELDMAPS -= [3]
$!ACTIVEFIELDMAPS += [2]
$!TWODAXIS YDETAIL{VARNUM = 2}
$!REDRAWALL 
$!EXTRACTFROMPOLYLINE 
  EXTRACTTHROUGHVOLUME = NO
  EXTRACTLINEPOINTSONLY = NO
  INCLUDEDISTANCEVAR = NO
  NUMPTS = 400
  EXTRACTTOFILE = YES
  FNAME = '.\Y.dat'
  RAWDATA
2
0 0.5 0
1.0 0.5 0
$!PICK SETMOUSEMODE
  MOUSEMODE = SELECT
$!RemoveVar |MFBD|
